### ISSUE TITLE
UUID? 

### ISSUE THREAD

**Issue by jimthedev** [kadirahq/graphql-errors#1]
Great idea, any chance you'd entertain providing a uuid with the internal error for easier log searching later on?

**Comment by arunoda** [comment]
Yeah! That's a pretty great idea. We'd love to have a PR for that :)

**Comment by thani-sh** [comment]
Added this feature with https://github.com/kadirahq/graphql-errors/pull/5

**Comment by thani-sh** [comment]
Deployed `v2.1.0` with the fix
