### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by danny-larsen** [kadirahq/graphql-errors#11]
We have a problem with the performance.
We are looking into it, but at first glance it looks like removing this, makes the queries roughly double speed.
If we remove the async/await from the resolvers the performance if fine, but error not handled.
Any ideas?

**Comment by LennyPenny** [comment]
Can you show me your testing methodology - very interested in using this but a perf hit this bad would suck

**Comment by mjasnikovs** [comment]
For graphqlExpress, remove **maskErrors** from schema, and use **formatError** option to parse error.

Something like this...
```JavaScript
app.use('/graphql', graphqlExpress(req => {
	return {
		schema,
		formatError: err => {
			if (err.stack === 'UserError') {
				return err
			}
			const errId = uuid.v4()
			err.message = `${err.message}: ${errId}`
			pino.error((err && err.stack) || err)
			err.message = `Internal Error: ${errId}`
			return err
		},
		context: Object.assign({},
			{
				session: req.context
			},
			databases
		)
	}
}))
```

**Comment by danny-larsen** [comment]
We actually ended up switching over to apollo-server-express and then using their formatError.
